### ISSUE TITLE
Player Weapons

### ISSUE THREAD

**Issue by joshheinrichs** [joshheinrichs/cmpt306-project#11]
Melee and ranged weapons. We don't have to decide on what they are yet really, just make them squares. 

It might be a good idea to make some sort of Damagable interface that applies to players, enemies, etc so we can generalize damaging characters.

**Comment by knames** [comment]
no weapons yet for the player, but projectiles can now do damage to the player instead of kill on hit, and enemies can melee the player. See 518214dd78a660557d4f0647baab2cf47f34fab0

**Comment by joshheinrichs** [comment]
Added a projectile weapon for the last milestone, probably won't add melee weapons
